server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1m

logging:
  level:
    com.flight.reservation: INFO
    org.springframework.cache: INFO
    org.springframework.web: INFO